Catch up with main trunk install/uninstall. Quiet output, etc.

diff --git a/GNUmakefile.in b/GNUmakefile.in
--- a/GNUmakefile.in
+++ b/GNUmakefile.in
@@ -1,6 +1,6 @@
 # Note:  Makefile is built automatically from Makefile.in
 #
-# $Id: GNUmakefile.in,v 1.104.2.20 2002/10/25 02:44:22 hal9 Exp $
+# $Id: GNUmakefile.in,v 1.104.2.21 2002/11/04 07:04:03 hal9 Exp $
 #
 # Written by and Copyright (C) 2001 the SourceForge
 # Privoxy team. http://www.privoxy.org/
@@ -51,6 +51,10 @@ SNAPVERSION   = $(RPM_VERSION)-$(shell date "+%Y%m%d")
 # "make install" directories and variables
 #############################################################################
 
+#User Group paras
+USER         = @USER@
+GROUP	   = @GROUP@
+
 prefix       = @prefix@
 exec_prefix  = @exec_prefix@
 CONF_BASE    = @sysconfdir@
@@ -77,14 +81,6 @@ PIDS_DEST    = $(VAR_DEST)/run
 # used in source dir only, the install goes to $share_dest/doc/privoxy
 DOK_WEB = doc/webserver/
 
-#############################################################################
-# Build tools
-#############################################################################
-
-PROGRAM    = privoxy@EXEEXT@
-CC         = @CC@
-ECHO       = echo
-GZIP_PROG  = gzip
 # Install usage should be compatible with install-sh.
 INSTALL    = @INSTALL@
 # Binaries
@@ -102,27 +98,40 @@ INSTALL_R  = -m $(RWD_MODE)
 
 # install options for superuser install
 #INSTALL_S  = -g @GROUP@ -o @USER@ 
+
+#############################################################################
+# Build tools
+#############################################################################
+
+PROGRAM    = privoxy@EXEEXT@
+CC         = @CC@
+ECHO       = echo
+GZIP_PROG  = gzip
+
 # id -u is not universal. FIXME: need to set from configure. Breaks on
 # Solaris.
 #ID         = id -u
-
+ID         = id
 LD         = @CC@
 RM         = rm -f
+CP         = cp -f
 RMDIR      = rmdir
 MKDIR      = ./mkinstalldirs
 STRIP_PROG = strip
-SED	   = sed
+SED	      = sed
 GREP       = grep
 CAT        = cat
 RPM        = rpm
 RPMBUILD   = rpmbuild
-MV	   = mv
+MV	      = mv
 TAR        = tar
 LN         = ln
 TOUCH      = touch
 KILL       = kill
 CHMOD      = chmod
 CHOWN      = chown
+CHGRP      = chgrp
+GROUPS     = groups
 WDUMP      = @WDUMP@ -dump
 JADECAT    = @JADECAT@
 JADEBIN    = @JADEBIN@
@@ -135,10 +144,6 @@ PERL       = perl
 DOC_DIR	 = doc/source
 DOC_TMP    = $(DOC_DIR)/tmp
 DOC_STATUS = @DOC_STATUS@
-
-#User Group paras
-USER       = @USER@
-GROUP	   = @GROUP@
 
 # Program to do LF->CRLF
 #
@@ -1045,30 +1050,31 @@ install-strip:
 #
 # FIXME: id handling needs help, probably via configure, since 'id -u' is not 
 # universally reliable (eg Solaris). Group handling could be better. 
-# Perhaps the whole user/group validation should be done here.
+# Perhaps the whole user/group validation should be done here, and simplified.
 PROGRAM_V = Privoxy $(VERSION)
 install: CONF_DEST LOG_DEST PID_DEST check_doc GROUP_T
-	# Quick test for valid USER.
-	if [ -n "$(USER)" ]; then \
-		id $(USER) >/dev/null || exit 1;\
+	@# Quick test for valid USER.
+	@if [ -n "$(USER)" ]; then \
+		$(ID) $(USER) >/dev/null || exit 1;\
 	fi
-	# Test for valid group.
-	if [ -n "$(GROUP_T)" ] && [ -n "$(USER)" ] && ! groups $(USER) | $(GREP) "\<$(GROUP_T)\>" >/dev/null; then \
-		$(ECHO) Group $(GROUP_T) for User $(USER) is invalid && exit 1 ;\
-	fi
+	@# Test for valid group. FIXME. USER does not have to belong to GROUP 
+	@# for file ownership purposes.
+# 	if [ -n "$(GROUP_T)" ] && [ -n "$(USER)" ] && ! $(GROUPS) $(USER) | $(GREP) "\<$(GROUP_T)\>" >/dev/null; then \
+# 		$(ECHO) Group $(GROUP_T) for User $(USER) is invalid && exit 1 ;\
+# 	fi
 	
-	$(ECHO) "Creating directories, and preparing $(PROGRAM_V) installation"
+	@$(ECHO) "Creating directories, and preparing $(PROGRAM_V) installation"
 	$(CHMOD) $(DIR_MODE) $(MKDIR)
-	$(MKDIR) $(SBIN_DEST) $(prefix) $(CONF_DEST) $(CONF_DEST)/templates $(SHARE_DEST) \
+	@$(MKDIR) $(SBIN_DEST) $(prefix) $(CONF_DEST) $(CONF_DEST)/templates $(SHARE_DEST) \
 		$(LOG_DEST) $(PID_DEST)
-	# Install the executable binary, strip if invoked as install-strip
-	test -n "$(STRIP)" &&\
+	@# Install the executable binary, strip if invoked as install-strip
+	@test -n "$(STRIP)" &&\
 	$(ECHO) Installing $(PROGRAM) stripped executable to $(SBIN_DEST) ||\
 	$(ECHO) Installing $(PROGRAM) executable to $(SBIN_DEST)
 	$(INSTALL) $(INSTALL_P) $(STRIP) $(PROGRAM) $(SBIN_DEST)
      
-	# Install the DOCS and man page 
-	-if [ $(check_doc) = 0 ]; then \
+	@# Install the DOCS and man page. install-sh only does one file at a time.
+	-@if [ $(check_doc) = 0 ]; then \
 		DOC=$(DOC_DEST) ;\
 	else \
 		DOC=$(prefix)/doc/privoxy ;\
@@ -1093,13 +1099,13 @@ install: CONF_DEST LOG_DEST PID_DEST check_doc GROUP_T
 		$(INSTALL) $(INSTALL_T) ChangeLog $$DOC;\
 		$(INSTALL) $(INSTALL_T) $(DOK_WEB)/p_doc.css $$DOC;\
 	fi
-	# Not all platforms support gzipped man pages.
-	$(ECHO) Installing man page to $(MAN_DEST)/privoxy.1
+	@# Not all platforms support gzipped man pages.
+	@$(ECHO) Installing man page to $(MAN_DEST)/privoxy.1
 	-$(INSTALL) $(INSTALL_T) privoxy.1  $(MAN_DEST)/privoxy.1
 
-	# Change the config file default directories according to the configured ones
-	$(ECHO) Rewriting config for this installation
-	if [ -f config.base ] ; then \
+	@# Change the config file default directories according to the configured ones
+	@$(ECHO) Rewriting config for this installation
+	@if [ -f config.base ] ; then \
 		$(CAT) config >config~ ;\
 		$(MV) config.base config ;\
 	fi
@@ -1108,53 +1114,57 @@ install: CONF_DEST LOG_DEST PID_DEST check_doc GROUP_T
 	$(MV) config config.base
 	$(MV) config.updated config 
 
-	# Install the config support files. Test for root install, and abort 
-	# if there is no privoxy user, and no other user was enabled during 
-	# configure. Later, install init script if appropriate.
-	$(ECHO) Installing templates to $(CONF_DEST)/templates
-	for i in `find templates -type f`; do \
+	@# Install the config support files. Test for root install, and abort 
+	@# if there is no privoxy user, and no other user was enabled during 
+	@# configure. Later, install init script if appropriate.
+	@$(ECHO) Installing templates to $(CONF_DEST)/templates
+	@for i in `find templates -type f`; do \
 		$(INSTALL) $(INSTALL_T) $$i $(CONF_DEST)/templates ;\
 	done
 
-	if [ "`id |sed 's/(.*//' |sed 's/.*=//'`" = "0" ] ;then\
+	@# FIXME: group/user validation is overly convoluted.
+	@# If superuser install ... we require a minimum of group ownership
+	@# of those files the daemon writes to, to be non-root owned.
+	@if [ "`$(ID) |sed 's/(.*//' |sed 's/.*=//'`" = "0" ] ;then\
 		if [ x$(USER) = x ] || [ $(USER) = root ]; then \
-			if [ "`id privoxy`" ]; then \
-				$(ECHO) "Warning: Setting user and group to privoxy";\
-				INSTALL_CONF="$(INSTALL_T) -g privoxy -o privoxy" ;\
-				USER=privoxy ;\
-				GROUP_T=privoxy ;\
+			if [ x$(GROUP) = x ] || [ $(GROUP) = root ]; then \
+				if [ "`$(ID) privoxy`" ] && \
+					$(GROUPS) privoxy | $(SED) 's/^.*://' |$(GREP) "\<privoxy\>" >/dev/null; then \
+					$(ECHO) "Warning: Setting group owner to privoxy";\
+					GROUP_T=privoxy ;\
+				else \
+					$(ECHO)  "******************************************************************" ;\
+					$(ECHO)  " WARNING! WARNING! installing config files as root!" ;\
+					$(ECHO)  " It is strongly recommended to run $(PROGRAM) as a non-root user," ;\
+					$(ECHO)  " and to install the config files as that user and/or group!" ;\
+					$(ECHO)  " Please read INSTALL, and create a privoxy user and group!" ;\
+					$(ECHO)  "*******************************************************************" ;\
+					exit 1 ;\
+				fi ;\
 			else \
-				$(ECHO)  "******************************************************************" ;\
-				$(ECHO)  " WARNING! WARNING! installing config files as root!" ;\
-				$(ECHO)  " It is strongly recommended to run $(PROGRAM) as non-root user," ;\
-				$(ECHO)  " and to install the config files as that user!" ;\
-				$(ECHO)  " Please read INSTALL, and create a privoxy user!" ;\
-				$(ECHO)  "*******************************************************************" ;\
-				exit 1 ;\
+				GROUP_T=$(GROUP) ;\
 			fi ;\
+			INSTALL_CONF="$(INSTALL_R) -g $$GROUP_T " ;\
 		else \
 			$(ECHO) "Superuser install, installing config files as $(USER):$(GROUP_T)" ;\
-			INSTALL_CONF="$(INSTALL_T) -o $(USER) -g $(GROUP_T)" ;\
+			INSTALL_CONF="$(INSTALL_R) -o $(USER) -g $(GROUP_T)" ;\
+			GROUP_T=$(GROUP_T) ;\
 		fi ;\
 	else \
 		if [ ! "`id $(USER)`" = "`id`" ] ;then \
 			$(ECHO) "** WARNING ** current install user different from configured user!!" ;\
 			$(ECHO) "Edit may fail." ;\
 		fi ;\
-		INSTALL_CONF="$(INSTALL_T)" ;\
+		INSTALL_CONF="$(INSTALL_R)" ;\
 	fi ;\
 	$(ECHO) Installing configuration files to $(CONF_DEST);\
 	for i in $(CONFIGS); do \
 		if [ -s "$(CONF_DEST)/$$i" ] ; then \
 			$(ECHO) Installing $$i as $$i.new ;\
-			$(INSTALL) $(INSTALL_R) $$i $(CONF_DEST)/$$i.new || exit 1;\
+			$(INSTALL) $$INSTALL_CONF $$i $(CONF_DEST)/$$i.new || exit 1;\
 			NEW=1;\
 		else \
-			if test "$$i" = "config" || test "$$i" = "default.filter"; then \
-				$(INSTALL) $(INSTALL_R) $$i $(CONF_DEST) || exit 1;\
-			else \
-				$(INSTALL) $(INSTALL_R) $$INSTALL_CONF $$i $(CONF_DEST) || exit 1;\
-			fi;\
+			$(INSTALL) $$INSTALL_CONF $$i $(CONF_DEST) || exit 1;\
 		fi ;\
 	done ;\
 	if [ -n "$$NEW" ]; then \
@@ -1163,9 +1173,13 @@ install: CONF_DEST LOG_DEST PID_DEST check_doc GROUP_T
 	fi ;\
 	[ ! -f $(LOG_DEST)/logfile ] && $(ECHO) Creating logfiles in $(LOG_DEST) || \
 		$(ECHO) Checking logfiles in $(LOG_DEST) ;\
-	$(TOUCH) $(LOG_DEST)/logfile $(LOG_DEST)/jarfile || exit 1 ;\
+		$(TOUCH) $(LOG_DEST)/logfile $(LOG_DEST)/jarfile || exit 1 ;\
 	if [ x$$USER != x ]; then \
-		$(CHOWN) $$USER:$$GROUP_T $(LOG_DEST)/logfile $(LOG_DEST)/jarfile || \
+		$(CHOWN) $$USER $(LOG_DEST)/logfile $(LOG_DEST)/jarfile || \
+		$(ECHO) "** WARNING ** current install user different from configured user. Logging may fail!!" ;\
+	fi ;\
+	if [ x$$GROUP_T != x ]; then \
+		$(CHGRP) $$GROUP_T $(LOG_DEST)/logfile $(LOG_DEST)/jarfile || \
 		$(ECHO) "** WARNING ** current install user different from configured user. Logging may fail!!" ;\
 	fi ;\
 	$(CHMOD) $(RWD_MODE) $(LOG_DEST)/logfile $(LOG_DEST)/jarfile || exit 1 ;\
@@ -1187,7 +1201,7 @@ install: CONF_DEST LOG_DEST PID_DEST check_doc GROUP_T
 			$(INSTALL) $(INSTALL_P) init.tmp /etc/rc.d/init.d/privoxy && $(RM) init.tmp;\
 			$(MKDIR) /etc/logrotate.d/ ;\
 			$(ECHO) "Installing logrotate script to /etc/logrotate.d/" ;\
-			$(INSTALL) $(INSTALL_P) privoxy.logrotate /etc/logrotate.d/privoxy ;\
+			$(INSTALL) -m 0644 privoxy.logrotate /etc/logrotate.d/privoxy ;\
 		elif [ -d /etc/init.d ] && [ -w /etc/init.d ] ; then \
 			$(ECHO) "Installing generic init script to /etc/init.d/privoxy" ;\
 			$(ECHO) "Please check that the PATHs are correct, and edit if needed." ;\
@@ -1196,75 +1210,91 @@ install: CONF_DEST LOG_DEST PID_DEST check_doc GROUP_T
 	else \
 		$(ECHO) "No init script installed, install it manually if needed" ;\
 	fi
-	# mmmmm, good.
+	@# mmmmm, good.
 	@$(ECHO) "$(PROGRAM_V) installation succeeded!"
 	@$(ECHO) "The Privoxy configuration files have been installed in $(CONF_DEST)"
 
 # rmdir is used as a precaution since it will not remove non-empty
 # directories. RH init script creates lock file and pid file.
 uninstall: CONF_DEST LOG_DEST PID_DEST check_doc
-	$(ECHO) Starting Privoxy uninstallation
-	# KILL privoxy if running
-	-if [ -f /etc/redhat-release ] && [ -d /etc/rc.d/init.d/ ] && [ -w /etc/rc.d/init.d/ ] ; then \
+	@$(ECHO) Starting Privoxy uninstallation
+	@# KILL privoxy if running
+	-@if [ -f /etc/redhat-release ] && [ -x /etc/rc.d/init.d/privoxy ]; then \
 		/etc/rc.d/init.d/privoxy stop >/dev/null 2>/dev/null ;\
 		chkconfig --del $(PROGRAM) 2>/dev/null;\
 	fi
-	-@ test -f $(PID_DEST)/privoxy.pid && $(ECHO) Stopping $(PROGRAM) &&\
-          $(KILL) `$(CAT) $(PID_DEST)/privoxy.pid` 
-	-@ test -f /var/run/privoxy.pid && $(ECHO) Stopping $(PROGRAM) &&\
-          $(KILL) `$(CAT) /var/run/privoxy.pid `
+	-@test -f $(PID_DEST)/privoxy.pid && $(ECHO) Stopping $(PROGRAM) &&\
+         $(KILL) `$(CAT) $(PID_DEST)/privoxy.pid` || :
+	-@test -f /var/run/privoxy.pid && $(ECHO) Stopping $(PROGRAM) &&\
+          $(KILL) `$(CAT) /var/run/privoxy.pid ` || :
 
-	# Program binary
-	$(ECHO) Removing $(PROGRAM) binary
+	@# Program binary
+	@$(ECHO) Removing $(PROGRAM) binary
 	$(RM) $(SBIN_DEST)/$(PROGRAM) $(SBIN_DEST)/$(PROGRAM)~
 
-	# config files and dir, and maybe old install backups
-	$(ECHO) Removing $(PROGRAM) config files
-	for i in $(CONFIGS); do \
+	@# config files and dir, and maybe old install backups
+	-@if [ -d $(CONF_DEST) ]; then \
+		$(ECHO) Saving $(PROGRAM) config files to /tmp/$(PROGRAM)-save ;\
+		$(MKDIR) /tmp/$(PROGRAM)-save ;\
+		cd $(CONF_DEST) ;\
+		for i in $(CONFIGS); do \
+			[ -f $$i ] && $(CP) $$i /tmp/$(PROGRAM)-save ;\
+		done ;\
+	fi
+	@$(ECHO) Removing $(PROGRAM) config files
+	-@for i in $(CONFIGS); do \
+		test -f $(CONF_DEST)/$$i && $(ECHO) Removing $$i ;\
 		$(RM) $(CONF_DEST)/$$i $(CONF_DEST)/$$i~ $(CONF_DEST)/$$i.new ;\
 	done
-	$(RM) -r $(CONF_DEST)/templates
+	-@test -d $(CONF_DEST)/templates && $(RM) -r $(CONF_DEST)/templates &&\
+	$(ECHO) "Removing $(CONF_DEST)/templates/*"
 	
-	# man page and docs
-	$(ECHO) Removing $(PROGRAM) docs
+	@# man page and docs
+	@$(ECHO) Removing $(PROGRAM) docs
 	-$(RM) $(MAN_DEST)/privoxy.1*
 	-$(RM) -r $(DOC_DEST) || $(RM) -r $(prefix)/doc/privoxy
 
-	# Log and jarfile and pidfile
-	$(ECHO) Removing $(PROGRAM) logs
+	@# Log and jarfile and pidfile
+	@$(ECHO) Removing $(PROGRAM) logs
 	-$(RM) $(LOG_DEST)/logfile $(PID_DEST)/privoxy.pid $(LOG_DEST)/jarfile
 
-	# Final clean up of unused directories. Special handling of CONF and LOG
+	@# Final clean up of unused directories. Special handling of CONF and LOG
      # destinations.
-	$(ECHO) Removing $(PROGRAM) directories
-	for i in $(LOG_DEST) $(CONF_DEST); do \
+	@$(ECHO) Removing $(PROGRAM) directories
+	@for i in $(LOG_DEST) $(CONF_DEST); do \
 		if test -d $$i; then \
+			$(ECHO) Removing $$i ;\
 			$(RMDIR) $$i || $(ECHO) "$$i is not empty, not removed" ;\
 		fi;\
 	done
-	if [  ! "$(prefix)" = "/usr/local" ] ;then \
+	@if [  ! "$(prefix)" = "/usr/local" ] ;then \
 		for i in $(MAN_DEST) $(MAN_DIR) $(SHARE_DEST)/doc $(SHARE_DEST) $(SBIN_DEST); do \
 			if test -d $$i; then \
+				$(ECHO) Removing $$i ;\
 				$(RMDIR) $$i || $(ECHO) "$$i is not empty, not removed" ;\
 			fi;\
 		done;\
 		if test $(LOG_DEST) != /var/log/privoxy && test -d $(prefix)/var/log; then \
+			$(ECHO) Removing $(prefix)/var/log ;\
 			$(RMDIR) $(prefix)/var/log || $(ECHO) "$(prefix)/var/log is not empty, not removed";\
 		fi ;\
 		if test $(PID_DEST) != /var/run && test -d $(prefix)/var/run; then \
+			$(ECHO) Removing $(prefix)/var/run ;\
 			$(RMDIR) $(prefix)/var/run || $(ECHO) "$(prefix)/var/run is not empty, not removed";\
 		fi ;\
 		if test $(prefix)/var != /var && test -d $(prefix)/var; then \
+			$(ECHO) Removing $(prefix)/var ;\
 			$(RMDIR) $(prefix)/var || $(ECHO) "$(prefix)/var is not empty, not removed" ;\
 		fi ;\
 		if test $(prefix) != / && test $(prefix) != /usr && test -d $(prefix); then \
+			$(ECHO) Removing $(prefix) ;\
 			$(ECHO) Removing installation directory $(prefix) ;\
 			$(RMDIR) $(prefix) || $(ECHO) "$(prefix) is not empty, not removed" ;\
 		fi;\
 	fi
 
-	# init scripts and logrotate
-	if [ "$(prefix)" = "/usr/local" ] || [ "$(prefix)" = "/usr" ]; then \
+	@# init scripts and logrotate
+	@if [ "$(prefix)" = "/usr/local" ] || [ "$(prefix)" = "/usr" ]; then \
 		$(ECHO) Removing $(PROGRAM) init script ;\
 		if [ -f /etc/slackware-version ] && [ -d /etc/rc.d/ ]  && [ -w /etc/rc.d/ ] ; then \
 			$(RM) /etc/rc.d/rc.privoxy ;\
@@ -1276,8 +1306,7 @@ uninstall: CONF_DEST LOG_DEST PID_DEST check_doc
 			$(ECHO) "Unable to remove privoxy init script, not installed or permission denied" ;\
 		fi ;\
 	fi
-	$(ECHO) Privoxy uninstalled, bye
-
+	@$(ECHO) Privoxy uninstalled, bye
 
 coffee:
 	 @perl -e 'print pack "C*", (31,139,8,8,153,63,226,60,2,3,99,111,102,102,101,101,0,109,143,205,13,192,32,8,133,\
@@ -1293,6 +1322,9 @@ coffee:
 ## end:
 
 # $Log: GNUmakefile.in,v $
+# Revision 1.104.2.21  2002/11/04 07:04:03  hal9
+# Catch up with main trunk install/uninstall. Quiet output, etc.
+#
 # Revision 1.104.2.20  2002/10/25 02:44:22  hal9
 # Port of make install, etc from main trunk. Needs testing! Add Slackware
 # support, and other related changes. Update related docs.
